//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboCup.AtHome.EGPSRCmdGen {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoboCup.AtHome.EGPSRCmdGen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #
        ///# This grammar file has no main, therefore, cannot be loaded
        ///# standalone. Import using:
        ///# ; import common.txt
        ///#
        ///# The following rules must be defined in the importer
        ///# ; An object type
        ///# $object
        ///# ; Rule for finding a specific (named) person
        ///# $findp
        ///# ; A named or described person in the given place
        ///# $whowhere
        ///#
        ///; grammar name Common
        ///
        ///##############################################################################
        ///#
        ///# Manipulation
        ///#
        ///##################################################### [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CommonRules {
            get {
                return ResourceManager.GetString("CommonRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ; grammar name GPSR Grammar
        ///; grammar tier High
        ///
        ///
        ///$Main      = $task
        ///$Main      = $polite $task
        ///$Main      = $task $please
        ///
        ///
        ///# Tasks
        ///####################################################################
        ///; Bring from description
        ///$task      = $bringdesc
        ///
        ///; Bring from/to storage
        ///$task      = $store
        ///
        ///; Bring to person matching description
        ///$task      = bring the {object} to the $person in the $room
        ///
        ///; Complex commands
        ///$task      = $triple
        ///$task      = $singleI, $single, and ($single | $singl [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EGPSRGrammar {
            get {
                return ResourceManager.GetString("EGPSRGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/FormatSpecification.txt.
        /// </summary>
        internal static string FormatSpecification {
            get {
                return ResourceManager.GetString("FormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/Gestures.xml.
        /// </summary>
        internal static string Gestures {
            get {
                return ResourceManager.GetString("Gestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/GrammarHeader.txt.
        /// </summary>
        internal static string GrammarHeader {
            get {
                return ResourceManager.GetString("GrammarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/Locations.xml.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/Names.xml.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/Objects.xml.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../CommonFiles/Questions.xml.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
    }
}
